### ISSUE TITLE
Affe seems to hang on Windows

### ISSUE THREAD

**Issue by oantolin** [minad/affe#11]
I tried `afffe-grep` on Windows and no prompt appears, I type and nothing happens, the minibuffer prompt does not appear. Fortunately when I press `C-g` the command does get canceled and then the characters I've been typing get inserted at point!

I thought maybe I had some problem with ripgrep or it's path (even though I remembered having figured this out for Windows at some point), but I doubt that's the problem since `consult-ripgrep` works just fine.

I'll try debugging a bit and will comment with any new information.

**Comment by minad** [comment]
1. We should add an ` *affe-log*` buffer which shows the stderr redirected from the producer process. See also `affe--backend-debug` which should be rewritten to write to the log buffer.
2. Maybe there is a problem with unix sockets, which I am using exclusively here. See `server-eval-at` vs `affe--connect`.

**Comment by minad** [comment]
I added `affe-backend--log` and an ` *affe*` buffer.

**Comment by bodnarlajos** [comment]
Hi,
I think we need to use the runemacs.exe instead of the emacs.exe when you start the emacs daemon.
The dirty fix is: (setq invocation-name "runemacs.exe")
But I got an other message : Buffer *scratch* has no process
I have a running daemon process with an affect-... file in the server folder.
I have not enough time to proceed the investigation but maybe you can give an advice :)

**Comment by minad** [comment]
Even plain `consult-ripgrep` makes issues on windows, see https://github.com/minad/consult/issues/317. Therefore I am not hopeful regarding to supporting Affe on Windows. Closing as wontfix.
