### ISSUE TITLE
[Feature request] Add ignore file list or ?

### ISSUE THREAD

**Issue by 404cn** [minad/affe#2]

**Comment by minad** [comment]
Files should be ignored by the producer process. Additional support in the affe frontend this is not planned. 

You can do two things to ignore files:

* Configure `affe-find-command` such that more files are excluded
* Use `fd` instead of `find`, which respects the `.gitignore` for example

Furthermore `affe-grep` uses `ripgrep`, which also respects the `.gitignore` file.
